export enum Flow {
  OK_CONT_FAIL_REVERT = "OK_CONT_FAIL_REVERT",
  OK_CONT_FAIL_STOP = "OK_CONT_FAIL_STOP",
  OK_CONT_FAIL_CONT = "OK_CONT_FAIL_CONT",
  OK_REVERT_FAIL_CONT = "OK_REVERT_FAIL_CONT",
  OK_REVERT_FAIL_STOP = "OK_REVERT_FAIL_STOP",
  OK_STOP_FAIL_CONT = "OK_STOP_FAIL_CONT",
  OK_STOP_FAIL_REVERT = "OK_STOP_FAIL_REVERT",
}

export default { Flow };
