name: 'dist push'

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update version
        run: git config --global user.email "bigcheeseh@gmail.com" && git config --global user.name "bigcheeseh" && yarn version --patch
      - name: stage changed files
        run: git add .
      - name: push updated version to current branch
        run: git push -f origin HEAD:${{ github.head_ref }}